### ISSUE TITLE
tx.h:109:78: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result

### ISSUE THREAD

**Issue by osalbahr** [ShawnZhong/MadFS#361]
Hi, out of experimentation I tried compiling MadFS on GitHub Codespaces (hoping to then write a mini CI that just tries to verify whether MadFS compiles on the `ubuntu-latest` GitHub runner).

Is this error expected? If not then I believe an explicit cast might be needed.
```console
@osalbahr ➜ /workspaces/MadFS (main) $ make BUILD_TARGETS="madfs"
cmake -S . -B build-release -DCMAKE_BUILD_TYPE=release 
-- Configuring done
-- Generating done
-- Build files have been written to: /workspaces/MadFS/build-release
cmake --build build-release -j --target madfs -- --quiet 
[ 72%] Built target pmem2
[ 74%] Building CXX object CMakeFiles/madfs.dir/src/file/write.cpp.o
[ 75%] Building CXX object CMakeFiles/madfs.dir/src/file/read.cpp.o
In file included from /workspaces/MadFS/src/tx/write.h:3,
                 from /workspaces/MadFS/src/tx/write_aligned.h:1,
                 from /workspaces/MadFS/src/file/write.cpp:2:
/workspaces/MadFS/src/tx/tx.h: In member function ‘bool madfs::dram::Tx::handle_conflict(madfs::pmem::TxEntry, madfs::VirtualBlockIdx, madfs::VirtualBlockIdx, std::vector<madfs::BaseIdx<unsigned int, madfs::IdxType::LOGICAL_BLOCK_IDX> >&, bool*)’:
/workspaces/MadFS/src/tx/tx.h:109:78: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
  109 |         VirtualBlockIdx end_vidx = curr_entry.inline_entry.begin_virtual_idx +
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  110 |                                    curr_entry.inline_entry.num_blocks;
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
In file included from /workspaces/MadFS/src/tx/read.h:3,
                 from /workspaces/MadFS/src/file/read.cpp:1:
/workspaces/MadFS/src/tx/tx.h: In member function ‘bool madfs::dram::Tx::handle_conflict(madfs::pmem::TxEntry, madfs::VirtualBlockIdx, madfs::VirtualBlockIdx, std::vector<madfs::BaseIdx<unsigned int, madfs::IdxType::LOGICAL_BLOCK_IDX> >&, bool*)’:
/workspaces/MadFS/src/tx/tx.h:109:78: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
  109 |         VirtualBlockIdx end_vidx = curr_entry.inline_entry.begin_virtual_idx +
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  110 |                                    curr_entry.inline_entry.num_blocks;
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
cc1plus: all warnings being treated as errors
make[4]: *** [CMakeFiles/madfs.dir/build.make:102: CMakeFiles/madfs.dir/src/file/read.cpp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[4]: *** [CMakeFiles/madfs.dir/build.make:141: CMakeFiles/madfs.dir/src/file/write.cpp.o] Error 1
make[3]: *** [CMakeFiles/Makefile2:365: CMakeFiles/madfs.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:372: CMakeFiles/madfs.dir/rule] Error 2
make[1]: *** [Makefile:236: madfs] Error 2
make: *** [Makefile:16: release] Error 2
```

Might be related:
https://github.com/ShawnZhong/MadFS/blob/7514a7816d39b95c9f34555a13c50173c4fa2b32/CMakeLists.txt#L13

**Comment by chenhao-ye** [comment]
Thanks for letting us know. I did a quick experiment on a Ubuntu 22 machine but didn't get the same error. We will try `ubuntu-latest` later.

The issue here is a little weird because both `curr_entry.inline_entry.begin_virtual_idx` and `curr_entry.inline_entry.num_blocks` are `uint32_t`, and `VirtualBlockIdx` constructors also accept only `uint32_t`. There is no `int` here.

Overall, the sign issue should just be a warning, but we enable the most strict compile flags to treat all warnings as errors, which stops the compiling. If this blocks you, you can try removing `-Werror` as a temporary workaround while we are investigating.

**Comment by chenhao-ye** [comment]
I ran a few experiments on both GitHub codespace and Docker containers with different Ubuntu releases. I think it's a bug of `g++-9`, which was fixed in `g++-10`; the solution is to install `g++-10` as documented in [Prerequisites](https://github.com/ShawnZhong/MadFS?tab=readme-ov-file#prerequisites). To confirm you are using the right compiler version, you should be able to see `cmake` printing `-- The CXX compiler identification is XXX` to the screen, where `XXX` is the compiler with the version info.

The default GitHub codespace uses Ubuntu 20, which comes with `g++-9` as the default `g++`. I can reproduce the problem on a GitHub codespace VM and a Ubuntu 20 docker container. The problem is gone after installing `g++-10`.

Hope this helps!

**Comment by osalbahr** [comment]
> I ran a few experiments on both GitHub codespace and Docker containers with different Ubuntu releases. I think it's a bug of `g++-9`, which was fixed in `g++-10`; the solution is to install `g++-10` as documented in [Prerequisites](https://github.com/ShawnZhong/MadFS?tab=readme-ov-file#prerequisites). To confirm you are using the right compiler version, you should be able to see `cmake` printing `-- The CXX compiler identification is XXX` to the screen, where `XXX` is the compiler with the version info.

Ah, that makes sense. Thx! I was a bit puzzled because `g++-10` was indeed installed (though installed after getting the error).

After some experimentation, I discovered this doesn't work (probably because `CXX` doesn't get set correctly, for some reason):
```console
$ make BUILD_TARGETS="madfs" || sudo apt install -y g++-10 && make BUILD_TARGETS="madfs"
[same error]
```

But *this* succeeds (note the `make clean`):
```console
$ make BUILD_TARGETS="madfs" || sudo apt install -y g++-10 && make clean && make BUILD_TARGETS="madfs"
[no error]
```

I'm not sure how much effort is needed to fix this `make` quirk. I'd say it's probably not worth it.

Closing since `g++-10` being a prerequisite is documented. It's a reasonable expectation to install the prerequisites, well.... beforehand, rather than trying to fix errors on the fly :)
